name: CI with Carbon Tracking

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-with-carbon-tracking:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    # Start energy measurement
    - name: Start Energy Measurement
      uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
      with:
        task: start-measurement
      env:
        ECO_CI_API_TOKEN: "maqbCvGDj1iRRtWc07AX"
    
    # Your CI tasks here
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    
    # End measurement and show results
    - name: End Energy Measurement and Display Results
      uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
      with:
        task: display-results
      env:
        ECO_CI_API_TOKEN: "maqbCvGDj1iRRtWc07AX"
    
    # Optional: Upload energy consumption data as artifact
    - name: Upload energy consumption data
      uses: actions/upload-artifact@v4
      with:
        name: energy-consumption-report
        path: |
          *.json
          total_energy_consumption-*.json
      if: always()
