name: Simple Eco CI Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  simple-carbon-test:
    runs-on: ubuntu-latest
    
    steps:
      # Start measurement
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de # v5.0.0
        with:
          task: start-measurement
          branch: ${{ github.head_ref || github.ref_name }}
        continue-on-error: true
      
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      # Simple test task - just wait and do basic operations
      - name: Simple CPU Task
        run: |
          echo "Starting simple CPU task..."
          python3 -c "
          import time
          import math
          
          print('Running simple computation for 30 seconds...')
          start_time = time.time()
          result = 0
          
          while time.time() - start_time < 30:
              for i in range(10000):
                  result += math.sqrt(i * 2.5)
          
          print(f'Computation completed. Final result: {result}')
          "
      
      # Get measurement after the task
      - name: Task Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de # v5.0.0
        with:
          task: get-measurement
          label: 'Simple CPU task'
        continue-on-error: true
      
      # Display results
      - name: Show Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de # v5.0.0
        with:
          task: display-results
        continue-on-error: true
