name: Debug Eco-CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Start Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: start-measurement
          calculate-co2: true
          co2-calculation-method: 'constant'
          co2-grid-intensity-constant: 432
          send-data: true
      - name: Dummy Work
        run: |
          echo "Doing some work..."
          sleep 10
          stress --cpu 1 --timeout 10s || echo "stress not available, using alternatives"
          for i in {1..1000000}; do echo $i > /dev/null; done
      - name: Get Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: get-measurement
          label: 'dummy work'
      - name: Display Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: display-results
          display-table: true
