name: CI with Eco-CI

on: [push, pull_request]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: start-measurement

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install -r requirements.txt || true

      - name: Post-Setup Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: get-measurement
          label: "Setup"

      - name: Run Script
        run: python main.py

      - name: Execution Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: get-measurement
          label: "Script Execution"

      - name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: display-results
